### ISSUE TITLE
docker数据可否持久化？

### ISSUE THREAD

**Issue by charley008** [ourongxing/newsnow#29]
如何持久化数据？每次更新都会导致之前的关注消失，又得重新搞一次。还有 财联社 头条一直刷不出来，但是财联社电报是可以刷出来的。

**Comment by charley008** [comment]
get cls-depth cache

TypeError: Cannot read properties of undefined (reading 'depth_list')

    at Object.cls-depth (file:///usr/app/output/server/chunks/_/getters.mjs:2360:19)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async Object.handler (file:///usr/app/output/server/chunks/routes/api/index2.mjs:61:24)

    at async Object.handler (file:///usr/app/output/server/chunks/nitro/nitro.mjs:2803:19)

    at async Server.toNodeHandle (file:///usr/app/output/server/chunks/nitro/nitro.mjs:3074:7)

**Comment by ourongxing** [comment]
cls-depth 已失效。持久化的问题，不都是存在浏览器里吗，链接不变数据就不会丢。至于 docker 数据持久化，我不太了解，这个项目主要部署在 cloudflare，可能需要其他人来解决这个问题，应该很容易。

**Comment by charley008** [comment]
终于找到默认数据库位置。
    volumes:
      - /docker/newsnow/:/usr/app/.data
